"""
LangGraph Shared State Architecture for FinSight AI.

This module defines the central state object passed between all agents in the LangGraph workflow.
It uses TypedDict, which is the recommended approach for LangGraph state management.
The state is highly modular to support future additions such as RAG context, 
human-in-the-loop approvals, and guardrail evaluations without causing bloat.
"""
from typing import TypedDict, List, Dict, Any, Optional, Annotated
import operator
from datetime import datetime

# ==========================================
# Modular Sub-States
# Structuring the state modularly keeps it extensible.
# ==========================================

class SessionInfo(TypedDict):
    """Tracks the current execution session and metadata."""
    session_id: str
    created_at: datetime
    workflow_stage: str
    # Future Human-in-the-loop: track if the graph is paused waiting for human approval
    requires_human_approval: bool

class DatasetInfo(TypedDict):
    """Details about the raw uploaded dataset."""
    filename: str
    file_type: str
    dataset_category: str
    business_domain: str
    raw_dataframe: Any  # Typed as Any to avoid strict Pandas dependency here, expects pd.DataFrame

class DatasetProfile(TypedDict):
    """Detailed metadata and statistics generated by the Data Auditor Agent."""
    overview: Dict[str, Any]
    columns: Dict[str, Any]

class QualityMetrics(TypedDict):
    """Scores (0-100) generated by the Data Auditor Agent."""
    scores: Dict[str, float]
    quality_grade: str  # A+, A, B+, B, C, D, F
    explanations: Dict[str, str]

class DatasetRisks(TypedDict):
    """PII and Business risk detection from Auditor."""
    risk_level: str
    risk_type: str
    affected_columns: List[str]
    recommendation: str

class ExecutionMetadata(TypedDict):
    """Workflow execution telemetry."""
    workflow_id: str
    execution_start: datetime
    execution_end: Optional[datetime]
    total_execution_time: float
    total_llm_calls: int
    provider: str
    dataset_hash: str
    input_tokens: int
    output_tokens: int
    total_tokens: int
    latency: float
    request_id: str
    estimated_llm_cost: float
    estimated_runtime: float
    prompt_version: str
    prompt_hash: str
    timeline: List[Dict[str, Any]]

class CleaningResults(TypedDict):
    """Results from the Cleaning Agent and Auditor recommendations."""
    cleaned_dataframe: Any  # Expects pd.DataFrame
    cleaning_summary: str
    detected_outliers: Dict[str, List[Any]]
    # Structured recommendations generated by the Auditor Agent
    cleaning_recommendations: List[Dict[str, str]]

class BusinessAnalytics(TypedDict):
    """
    Factual, deterministic analytics computed by the Business Analyst Agent.
    """
    calculated_kpis: Dict[str, Any]
    trend_analysis: Dict[str, Any]
    segment_analysis: Dict[str, Any]
    statistical_analysis: Dict[str, Any]
    anomaly_summary: List[str]
    visualization_recommendations: List[str]
    generated_exports: List[str]
    chart_paths: List[str]

class ChartMetadata(TypedDict):
    """Metadata for a generated chart."""
    chart_title: str
    chart_type: str
    x_axis: str
    y_axis: str
    aggregation: str
    sorting: str
    filter: str
    description: str

class Visualization(TypedDict):
    """Paths to charts and datasets generated for visualization."""
    # Richer structure to store chart metadata instead of just paths
    charts: List[ChartMetadata]
    tableau_export_path: str  # Path to CSV inside exports/tableau/

class AIInsights(TypedDict):
    """Insights and explanations generated by the Insight Agent."""
    executive_summary: str
    key_findings: List[Dict[str, Any]]
    business_risks: List[Dict[str, Any]]
    business_opportunities: List[Dict[str, Any]]
    recommendations: List[Dict[str, Any]]
    next_best_actions: List[Dict[str, Any]]
    data_quality_observations: List[str]
    confidence: float

class ValidationResult(TypedDict):
    """Validation result for a single generated insight."""
    insight: str
    status: str
    confidence_score: float
    hallucination_score: float
    consistency_score: float
    coverage_score: float
    evidence_score: float
    supporting_metrics: List[str]
    evidence_sources: List[str]
    validation_notes: List[str]
    warnings: List[str]

class Validation(TypedDict):
    """Guardrails and evaluation metrics generated by the Validation Agent."""
    validation_results: List[ValidationResult]
    overall_status: str
    average_confidence: float
    hallucination_rate: float
    unsupported_claims: List[str]

class Reports(TypedDict):
    """Export paths generated by the Report Agent."""
    # Stores the plain-text executive summary separately from generated files
    executive_summary: str
    markdown_report_path: str
    pdf_report_path: str
    html_report_path: str
    report_manifest: Dict[str, Any]

class WorkflowTracking(TypedDict):
    """LangGraph execution tracking and metadata."""
    # The ordered execution plan populated by the Planner Agent
    analysis_plan: List[str]
    # The reasoning generated by the Planner Agent for selecting the analyses
    planner_reasoning: List[str]
    # List of downstream agents required for this plan
    required_agents: List[str]
    # Confidence score from the Planner Agent LLM
    planner_confidence: float
    completed_agents: List[str]
    current_agent: str
    next_agent: str
    execution_time: float
    requires_manual_review: bool
    dataset_complexity: str
    execution_graph: List[str]

class AgentLog(TypedDict):
    """Execution log for an individual agent step."""
    agent_name: str
    status: str
    timestamp: datetime
    message: str
    # Execution metrics
    provider_used: Optional[str]
    llm_calls: int
    estimated_tokens: int
    estimated_cost: float
    warnings: List[str]

# ==========================================
# Central Shared State
# ==========================================

class FinSightState(TypedDict):
    """
    The master state object shared across all LangGraph nodes.
    """
    
    # 0. Execution Telemetry
    execution_metadata: ExecutionMetadata
    
    # 1. Session Information
    session_info: SessionInfo
    
    # 2. Dataset Information
    dataset_info: DatasetInfo
    
    # 3. Dataset Profile
    dataset_profile: DatasetProfile
    
    # 3b. Quality Metrics
    quality_metrics: QualityMetrics
    
    # 3c. Dataset Risks
    dataset_risks: List[DatasetRisks]
    
    # 4. Cleaning Results
    cleaning_results: CleaningResults
    
    # 5. Business Analytics
    business_analytics: BusinessAnalytics
    
    # 6. Visualization
    visualization: Visualization
    
    # 7. AI Insights
    ai_insights: AIInsights
    
    # 8. Validation (Guardrails / Evaluation)
    validation: Validation
    
    # 9. Reports
    reports: Reports
    
    # 10. Conversation
    # Collects the interactive Q&A after the workflow finishes
    chat_history: Annotated[List[Dict[str, str]], operator.add]
    
    # 11. Workflow Tracking
    workflow_tracking: WorkflowTracking
    
    # 12. Errors
    # Collects any exceptions or issues encountered during graph execution
    error_messages: Annotated[List[str], operator.add]
    
    # 13. Agent Execution Logs
    # Every completed agent appends one execution log for debugging and explainability
    agent_logs: Annotated[List[AgentLog], operator.add]
