"""
Planner Agent LangGraph Node.
Orchestrates domain heuristics, LLM invocation, caching, and dependency injection.
"""
import time
import json
from datetime import datetime, timezone
from typing import Dict, Any

from backend.state.state import FinSightState, AgentLog
from backend.utils.cache_manager import CacheManager
from backend.utils.logger import logger

from .planner_utils import determine_complexity, detect_domain_heuristics
from .planner_service import invoke_planner_llm
from .planner_models import PlannerOutput


def _prepare_auditor_summary(state: FinSightState) -> Dict[str, str]:
    """Extracts deterministic auditor outputs from state into prompt format."""
    dataset_profile = state.get("dataset_profile", {})
    quality_metrics = state.get("quality_metrics", {})
    dataset_risks = state.get("dataset_risks", [])
    
    col_profiles = dataset_profile.get("columns", {})
    simplified_cols = {}
    for col, data in col_profiles.items():
        simplified_cols[col] = {
            "type": data.get("datatype"),
            "semantic": data.get("inferred_semantic_type"),
            "cardinality": data.get("cardinality")
        }
        
    return {
        "dataset_name": state.get("dataset_info", {}).get("filename", "unknown"),
        "dataset_overview": json.dumps(dataset_profile.get("overview", {}), indent=2),
        "dataset_risks": json.dumps(dataset_risks, indent=2),
        "quality_metrics": json.dumps(quality_metrics.get("scores", {}), indent=2),
        "column_profiles": json.dumps(simplified_cols, indent=2)
    }

def planner_node(state: FinSightState) -> Dict[str, Any]:
    """
    Main execution block for the Planner Node within the LangGraph state machine.
    
    This agent acts as the strategic intelligence of the workflow. It reads the 
    `dataset_profile` generated by the Auditor Agent and formulates a deterministic
    `analysis_plan`. Crucially, this node does NOT analyze data values, but rather
    the *schema* of the data to decide which mathematical operations the downstream
    Analytics Agent should execute.
    
    The node utilizes `CacheManager` to hash the raw dataframe and prevent redundant
    LLM calls for datasets that have already been planned.
    
    Args:
        state (FinSightState): The global shared state containing the dataset profile.
        
    Returns:
        Dict[str, Any]: Partial state update containing the `analysis_plan`, `execution_graph`,
                        and `execution_metadata` telemetry.
    """
    start_time = time.time()
    agent_name = "Planner Agent"
    
    # Extract metadata
    raw_df = state.get("dataset_info", {}).get("raw_dataframe")
    dataset_hash = CacheManager.generate_hash(raw_df)
    execution_metadata = state.get("execution_metadata", {})
    workflow_tracking = state.get("workflow_tracking", {})
    dataset_profile = state.get("dataset_profile", {})
    overview = dataset_profile.get("overview", {})
    
    # 1. Dataset Complexity Heuristics
    complexity = determine_complexity(
        rows=overview.get("row_count", 0),
        cols=overview.get("column_count", 0),
        memory_mb=overview.get("memory_usage_mb", 0.0)
    )
    
    # 2. Cache Lookup
    cached_response = CacheManager.get(dataset_hash)
    if cached_response:
        logger.info(f"{agent_name}: Cache HIT for {dataset_hash}.")
        llm_output = PlannerOutput(**cached_response["data"])
        p_version = cached_response["prompt_version"]
        p_hash = cached_response["prompt_hash"]
        provider = "Cache"
        est_tokens = 0
        est_cost = 0.0
    else:
        logger.info(f"{agent_name}: Cache MISS for {dataset_hash}. Computing...")
        # Domain Heuristics
        cols = list(dataset_profile.get("columns", {}).keys())
        domain_hint = detect_domain_heuristics(cols)
        
        # Invoke LLM
        summary_data = _prepare_auditor_summary(state)
        gateway_response, p_version, p_hash = invoke_planner_llm(summary_data, domain_hint)
        
        if not gateway_response:
            logger.error("Planner failed gracefully.")
            return {"agent_logs": [{"agent_name": agent_name, "status": "FAILED", "timestamp": datetime.now(timezone.utc), "message": "LLM failed", "llm_calls": 1, "provider_used": "Unknown", "estimated_tokens": 0, "estimated_cost": 0.0, "warnings": ["Fallback"]}]}
            
        llm_output = gateway_response.data
        provider = gateway_response.provider
        est_tokens = gateway_response.estimated_tokens
        est_cost = gateway_response.estimated_cost
        
        # Save to Cache
        CacheManager.save(dataset_hash, {
            "data": llm_output.model_dump(),
            "prompt_version": p_version,
            "prompt_hash": p_hash
        })
        
    # 3. Planning Risks and Execution Graph Dependencies
    requires_manual_review = False
    reasoning = llm_output.reasoning
    execution_graph = llm_output.execution_graph
    
    if llm_output.confidence < 0.60:
        requires_manual_review = True
        reasoning.append("Manual Review Recommended: Confidence below threshold.")
        
    dataset_risks = state.get("dataset_risks", [])
    if dataset_risks and "Validation Agent" not in execution_graph:
        logger.info("High risk dataset detected. Automatically injecting Validation Agent.")
        if "Report Generator" in execution_graph:
            execution_graph.insert(execution_graph.index("Report Generator"), "Validation Agent")
        else:
            execution_graph.append("Validation Agent")
            
    # 4. Agent Logging & Telemetry
    execution_duration = time.time() - start_time
    log: AgentLog = {
        "agent_name": agent_name,
        "status": "COMPLETED",
        "timestamp": datetime.now(timezone.utc),
        "message": f"Planned {len(execution_graph)} nodes. Domain: {llm_output.business_domain}.",
        "provider_used": provider,
        "llm_calls": 0 if provider == "Cache" else 1,
        "estimated_tokens": est_tokens,
        "estimated_cost": est_cost,
        "warnings": ["Manual Review Recommended"] if requires_manual_review else []
    }
    
    # Merge existing telemetry
    total_tokens = execution_metadata.get("total_tokens", 0) + est_tokens
    total_cost = execution_metadata.get("estimated_llm_cost", 0.0) + est_cost
    total_llm = execution_metadata.get("total_llm_calls", 0) + (0 if provider == "Cache" else 1)
    
    return {
        "dataset_info": {
            **state.get("dataset_info", {}),
            "dataset_category": llm_output.dataset_type,
            "business_domain": llm_output.business_domain
        },
        "execution_metadata": {
            **execution_metadata,
            "dataset_hash": dataset_hash,
            "provider": provider,
            "prompt_version": p_version,
            "prompt_hash": p_hash,
            "input_tokens": est_tokens, # Proxy
            "output_tokens": 0,
            "total_tokens": total_tokens,
            "latency": execution_duration,
            "estimated_llm_cost": total_cost,
            "total_llm_calls": total_llm
        },
        "workflow_tracking": {
            **workflow_tracking,
            "analysis_plan": llm_output.analysis_plan,
            "planner_reasoning": reasoning,
            "required_agents": llm_output.required_agents,
            "execution_graph": execution_graph,
            "planner_confidence": llm_output.confidence,
            "dataset_complexity": complexity,
            "requires_manual_review": requires_manual_review,
            "current_agent": agent_name,
            "completed_agents": workflow_tracking.get("completed_agents", []) + [agent_name],
            "execution_time": execution_duration
        },
        "agent_logs": [log]
    }
