"""
Converts HTML to PDF using pdfkit.
Gracefully fails if wkhtmltopdf binaries are missing.
"""

import pdfkit
from backend.utils.logger import logger


def generate_pdf(html_text: str, output_path: str) -> bool:
    """Generate a PDF from HTML with professional formatting."""
    try:
        options = {
            "page-size": "A4",
            "margin-top": "20mm",
            "margin-right": "15mm",
            "margin-bottom": "20mm",
            "margin-left": "15mm",
            "encoding": "UTF-8",
            "no-outline": None,
            "quiet": "",
            "footer-center": "FinSight AI — Confidential",
            "footer-font-size": "8",
            "footer-line": "",
            "footer-right": "Page [page] of [topage]",
            "header-line": "",
            "header-font-size": "8",
            "header-right": "Generated by FinSight AI",
        }
        pdfkit.from_string(html_text, output_path, options=options)
        return True
    except Exception as e:
        logger.warning(f"PDF generation failed (wkhtmltopdf likely missing): {str(e)}")
        return False
