"""
Hallucination Detector for Validation Agent.
Identifies claims that lack any deterministic evidence.
"""
import re
from typing import List, Tuple
from backend.state.state import FinSightState
from .evidence_matcher import _flatten_kpis, _extract_numbers


def detect_hallucinations(insight: str, state: FinSightState) -> Tuple[float, List[str]]:
    """
    Scans an insight narrative for numerical, percentage, and trend claims that
    cannot be matched to any deterministic source from the Analytics Agent.

    This algorithm isolates generative math hallucinations by extracting numbers 
    via RegEx (`_extract_numbers`) and cross-referencing them against the flattened
    `state["business_analytics"]` dictionary with a 5% fuzziness tolerance.

    Args:
        insight (str): The narrative text generated by the LLM.
        state (FinSightState): The current graph state containing deterministic metrics.

    Returns:
        Tuple[float, List[str]]: 
            - A float (0.0 to 1.0) representing the hallucination ratio.
            - A list of string descriptions for every unsupported claim found.
    """
    analytics = state.get("business_analytics", {})
    kpis = analytics.get("calculated_kpis", {})
    trends = analytics.get("trend_analysis", {})
    stats = analytics.get("statistical_analysis", {})

    flat_kpis = _flatten_kpis(kpis)
    flat_stats = _flatten_kpis(stats)
    all_values = {**flat_kpis, **flat_stats}

    unsupported: List[str] = []
    checks = 0
    failures = 0

    insight_lower = insight.lower()

    # 1. Numerical claim validation
    numbers = _extract_numbers(insight)
    for num in numbers:
        checks += 1
        matched = any(
            abs(num - v) <= abs(v * 0.05)
            for v in all_values.values()
            if v != 0
        )
        if not matched:
            failures += 1
            unsupported.append(f"Numerical claim '{num}' not found in deterministic analytics.")

    # 2. Percentage claim validation
    pct_matches = re.findall(r'(\d+(?:\.\d+)?)\s*%', insight)
    for pct_str in pct_matches:
        checks += 1
        pct_val = float(pct_str)
        matched = any(
            abs(pct_val - v) <= abs(v * 0.05)
            for v in all_values.values()
            if v != 0
        )
        if not matched:
            failures += 1
            unsupported.append(f"Percentage claim '{pct_val}%' not found in deterministic analytics.")

    # 3. Trend direction claim validation
    trend_keywords = {
        "increasing": "increas",
        "decreasing": "decreas",
        "growing": "grow",
        "declining": "declin",
        "stable": "stable",
        "volatile": "volatil",
    }
    actual_trend = str(trends.get("Overall Trend", "")).lower()
    for label, keyword in trend_keywords.items():
        if keyword in insight_lower:
            checks += 1
            if actual_trend and keyword not in actual_trend:
                # Only flag if there IS an actual trend that contradicts
                if actual_trend not in ["", "unknown", "n/a"]:
                    failures += 1
                    unsupported.append(
                        f"Trend claim '{label}' contradicts actual trend '{actual_trend}'."
                    )

    hallucination_score = (failures / checks) if checks > 0 else 0.0
    return round(min(hallucination_score, 1.0), 3), unsupported
